name: Build Docker Image on PR

# Trigger the workflow when a pull request is opened or updated targeting the 'main' branch
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .  # Path to your Dockerfile
          file: ./Dockerfile  
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/startup_model:latest